ALTER TABLE utilisateur ALTER COLUMN nom TYPE TEXT;
ALTER TABLE utilisateur ALTER COLUMN mdp TYPE TEXT;
ALTER TABLE utilisateur ALTER COLUMN validation_token TYPE TEXT;
ALTER TABLE utilisateur ALTER COLUMN reset_token TYPE TEXT;





ALTER TABLE depense_detail ALTER COLUMN pu TYPE DOUBLE PRECISION;
ALTER TABLE depense_detail ALTER COLUMN qte TYPE DOUBLE PRECISION;