ALTER TABLE depense ADD COLUMN reste_a_payer DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE depense DROP  COLUMN reste_a_payer;
ALTER TABLE depense ADD COLUMN total_payer DOUBLE PRECISION NOT NULL DEFAULT 0.0;
